import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          <div className="min-h-screen">
            {" "}
            <main className="">
              {/* container to center the content */}
              <div className="">
                <div className="grid grid-cols-1 lg:grid-cols-12">
                  <div className="hidden lg:block lg:col-span-2">
                    <Sidebar />
                  </div>
                  <div className="lg:col-span-10">{children}</div>
                </div>
              </div>
            </main>
          </div>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
